# Generated by Django 5.0.2 on 2024-03-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='funcionarios',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='produto',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='funcionarios',
        ),
        migrations.DeleteModel(
            name='vendas',
        ),
    ]
